# Generated by Django 2.0.13 on 2019-05-05 19:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=5)),
                ('phone_number', models.CharField(max_length=13)),
                ('mentee_id', models.IntegerField()),
                ('mentor_id', models.IntegerField()),
                ('place', models.CharField(choices=[('seoul', 'seoul'), ('kyeonggi', 'kyeonggi'), ('chungcheong', 'chungcheong'), ('jeonra', 'jeonra'), ('kyeongsang', 'kyeongsang')], max_length=15)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=5)),
                ('mentee_id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=12)),
                ('subject', models.CharField(choices=[('korean', 'korean'), ('math', 'math'), ('science', 'science'), ('society', 'society'), ('english', 'english')], max_length=10)),
                ('place', models.CharField(choices=[('seoul', 'seoul'), ('kyeonggi', 'kyeonggi'), ('chungcheong', 'chungcheong'), ('jeonra', 'jeonra'), ('kyeongsang', 'kyeongsang')], max_length=15)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(default=1, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=5)),
                ('mentor_id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('subject', models.CharField(choices=[('korean', 'korean'), ('math', 'math'), ('science', 'science'), ('society', 'society'), ('english', 'english')], max_length=10)),
                ('place', models.CharField(choices=[('seoul', 'seoul'), ('kyeonggi', 'kyeonggi'), ('chungcheong', 'chungcheong'), ('jeonra', 'jeonra'), ('kyeongsang', 'kyeongsang')], max_length=15)),
                ('phone_number', models.CharField(max_length=12)),
                ('license', models.FileField(upload_to='uploads/')),
                ('text', models.TextField()),
                ('user', models.ForeignKey(default=1, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
