# Generated by Django 2.0.13 on 2019-05-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
