# Generated by Django 2.0.13 on 2019-05-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentee',
            old_name='mentee_id',
            new_name='id_mentee',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mentor_id',
            new_name='id_mentor',
        ),
    ]
