# Generated by Django 2.0.13 on 2019-05-05 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mentee_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=5)),
                ('phone_number', models.CharField(max_length=12)),
                ('subject', models.CharField(choices=[('korean', 'korean'), ('math', 'math'), ('science', 'science'), ('society', 'society'), ('english', 'english')], max_length=10)),
                ('place', models.CharField(choices=[('seoul', 'seoul'), ('kyeonggi', 'kyeonggi'), ('chungcheong', 'chungcheong'), ('jeonra', 'jeonra'), ('kyeongsang', 'kyeongsang')], max_length=15)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='text',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='mentee',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
