# Generated by Django 2.0.13 on 2019-05-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190506_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='user',
        ),
    ]
