# Generated by Django 2.0.13 on 2019-05-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190505_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
