# Generated by Django 2.0.13 on 2019-05-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='phone_number',
            field=models.CharField(default=10, max_length=12),
            preserve_default=False,
        ),
    ]
