# Generated by Django 2.0.13 on 2019-05-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=5)),
                ('phone_number', models.CharField(max_length=12)),
                ('subject', models.CharField(choices=[('korean', 'korean'), ('math', 'math'), ('science', 'science'), ('society', 'society'), ('english', 'english')], max_length=10)),
                ('place', models.CharField(choices=[('seoul', 'seoul'), ('kyeonggi', 'kyeonggi'), ('chungcheong', 'chungcheong'), ('jeonra', 'jeonra'), ('kyeongsang', 'kyeongsang')], max_length=15)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=5)),
                ('subject', models.CharField(choices=[('korean', 'korean'), ('math', 'math'), ('science', 'science'), ('society', 'society'), ('english', 'english')], max_length=10)),
                ('place', models.CharField(choices=[('seoul', 'seoul'), ('kyeonggi', 'kyeonggi'), ('chungcheong', 'chungcheong'), ('jeonra', 'jeonra'), ('kyeongsang', 'kyeongsang')], max_length=15)),
                ('license', models.FileField(upload_to='uploads/')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
