# Generated by Django 2.0.13 on 2019-05-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lions_edu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentee',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
